-- Add mascot image URL column to packets table
-- Generated by Replicate (black-forest-labs/flux-schnell) after packet creation.
-- Nullable — older packets and packets where generation failed will have null.

alter table packets
  add column if not exists mascot_image_url text;
