import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "See a Sample Packet",
  description:
    "Browse a real, full-length Packet Day packet — every page, no signup required.",
};

// Every page in public/sample/ was rasterized at the same width by
// scripts/convert-sample-pdf.ts, so the pixel dimensions are uniform.
const PAGE_WIDTH = 1200;
const PAGE_HEIGHT = 1553;
const PAGE_COUNT = 15;

const pages = Array.from({ length: PAGE_COUNT }, (_, i) => {
  const pageNum = i + 1;
  const isLast = pageNum === PAGE_COUNT;
  return {
    src: `/sample/page-${String(pageNum).padStart(2, "0")}.png`,
    alt: isLast
      ? "Sample packet, page 15 of 15 — parent answer sheet"
      : `Sample packet, page ${pageNum} of ${PAGE_COUNT}`,
  };
});

export default function SamplePage() {
  return (
    <main className="min-h-full">
      {/*
        TODO: placeholder copy — replace with real, brand-voice heading and
        intro before this route goes live. Keeping it obviously temporary on
        purpose.
      */}
      <div className="mx-auto max-w-2xl px-4 pt-12 pb-8 text-center">
        <h1 className="font-display text-3xl font-bold text-dark sm:text-4xl">
          [PLACEHOLDER] Here&apos;s a real Packet Day packet
        </h1>
        <p className="mt-4 text-base text-dark/70">
          [PLACEHOLDER INTRO — replace before launch] This is an actual
          packet generated by Packet Day, page by page, including the parent
          answer sheet at the end. No signup, no download — just scroll.
        </p>
      </div>

      <div className="mx-auto flex max-w-2xl flex-col gap-6 px-4 pb-16">
        {pages.map((page, i) => (
          <div
            key={page.src}
            className="overflow-hidden rounded-lg border border-dark/10 shadow-sm"
          >
            <Image
              src={page.src}
              alt={page.alt}
              width={PAGE_WIDTH}
              height={PAGE_HEIGHT}
              sizes="(min-width: 672px) 672px, 100vw"
              priority={i === 0}
              loading={i === 0 ? "eager" : "lazy"}
              className="h-auto w-full"
            />
          </div>
        ))}
      </div>

      {/*
        TODO: optional email capture goes here — not built yet.
        Should sit below the full packet scroll, framed as optional
        ("want one like this for your kid?"), never a wall blocking the
        images above. No signup requirement on this route until this
        section is deliberately built and wired up.
      */}
    </main>
  );
}
